DROP TABLE IF EXISTS auth_admin;
DROP TABLE IF EXISTS auth_function;
DROP TABLE IF EXISTS auth_menu;
DROP TABLE IF EXISTS auth_permission;
DROP TABLE IF EXISTS auth_role;
DROP TABLE IF EXISTS auth_role_permission;
DROP TABLE IF EXISTS auth_user;
DROP TABLE IF EXISTS auth_user_role;

CREATE TABLE `auth_admin` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `USER_ID` DOUBLE DEFAULT NULL COMMENT '用户ID',
   `NAME` VARCHAR(80) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
   `EMAIL` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
   `TEL` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '电话',
   `DEPART_ID` DOUBLE DEFAULT NULL COMMENT '部门ID(废弃)',
   `JOB_NO` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '工号',
   `TYPE` DOUBLE DEFAULT NULL COMMENT '类型',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_admin_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ;


CREATE TABLE `auth_function` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `PARENT_ID` DOUBLE DEFAULT NULL COMMENT '父功能点ID',
   `NAME` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '功能名称',
   `FUNCTION_INDEX` DOUBLE DEFAULT NULL COMMENT '排序索引',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_function_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='功能点表';

CREATE TABLE `auth_menu` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `PERMISSION` VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '权限ID',
   `PARENT_ID` DOUBLE DEFAULT NULL COMMENT '父菜单ID',
   `NAME` VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '菜单名称',
   `URL` VARCHAR(800) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '菜单URL',
   `MENU_INDEX` DOUBLE DEFAULT NULL COMMENT '排序索引',
   `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_menu_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='菜单表';

CREATE TABLE `auth_permission` (
   `PERMISSION` VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '权限',
   `NAME` VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '权限名称',
   `FUNCTION_ID` DOUBLE DEFAULT NULL COMMENT '功能ID',
   `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间'
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='权限表';

CREATE TABLE `auth_role` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `NAME` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '角色名称',
   `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_role_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=206 DEFAULT CHARSET=utf8 COMMENT='角色表';

CREATE TABLE `auth_role_permission` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `ROLE_ID` DOUBLE DEFAULT NULL COMMENT '角色ID',
   `PERMISSION` VARCHAR(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '权限ID',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_role_permission_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1953 DEFAULT CHARSET=utf8 COMMENT='角色权限关系表';

CREATE TABLE `auth_user` (
   `USER_ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '用户ID',
   `USERNAME` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户名称',
   `PASSWORD` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
   `USER_STATUS` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户状态',
   `USER_TYPE` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户类型',
   `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
   `LOCALE` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '语言（废弃）',
   PRIMARY KEY (`USER_ID`),
   UNIQUE KEY `auth_user_pk` (`USER_ID`),
   UNIQUE KEY `auth_user_uk1` (`USERNAME`)
) ENGINE=INNODB AUTO_INCREMENT=302 DEFAULT CHARSET=utf8 COMMENT='用户基本信息表';

CREATE TABLE `auth_user_role` (
   `ID` DOUBLE NOT NULL AUTO_INCREMENT COMMENT '主键',
   `USER_ID` DOUBLE DEFAULT NULL COMMENT '用户ID',
   `ROLE_ID` DOUBLE DEFAULT NULL COMMENT '角色ID',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `auth_user_role_pk` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=422 DEFAULT CHARSET=utf8 COMMENT='用户角色关系表';